***
# Basic Assisments
***

##  Write a Python function to check if a number is even

1

##  Write a Python function to find the factorial of a number.

[2, 5, 1, 10]

##  Write a Python function to check if a string is a palindrome.

'MAdAM is a palindrom'

## Write a Python function to return the Fibonacci series up to n terms.

[0, 1, 1, 2, 3, 5, 8]

##  Write a Python function to find the HCF
***

###
✅ **Yes, that is an excellent and accurate analogy** for understanding how **HCF works!**
Let me rephrase and expand it slightly to reinforce the concept:

---

### 🎯 Real-World Analogy Using HCF:

**You have:**

* 8 red balls
* 12 green balls

You want to:

* **Pack them into identical boxes** such that:

  * Each box has **the same number of red and green balls**
  * No balls are left over

---

### 🔍 Step-by-Step Thinking:

1. **Find the HCF of 8 and 12**

   * HCF(8, 12) = **4**

2. **What does that mean?**
   You can make **4 identical boxes**.

3. **Distribute balls equally:**

   * Red balls per box = 8 ÷ 4 = **2**
   * Green balls per box = 12 ÷ 4 = **3**

---

### ✅ Final Conclusion:

You can pack **2 red balls and 3 green balls per box**, and:

* You’ll have **4 such boxes**
* **No balls are left over**

---

### 📦 Why this analogy is useful:

* It shows **grouping or distributing** things evenly.
* Helps in understanding how HCF finds the **largest group size** that divides quantities **exactly and equally**.

---

Let me know if you'd like more such analogies (e.g., ropes, chocolates, scheduling events, etc.)!


1

20.0

***
# Intermediate Assisments
***

## Last Nth highest Number

real >> [12, 43, 534, 23, 43, 23345, 32, 13, 45]


43

## find N perfect square list of numbers

[1, 4, 9, 16, 25, 36, 49, 64, 81]

## Reverse the numbers

321

## print N sliding window on given M range also print the reminder if any
- formula (start * size to start * size + size)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]  1 batch
[55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]  2 batch
[6765, 10946]  3 batch


## print N sliding window with overlap of M size


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
[17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
[25, 26, 27, 28, 29, 30, 31, 32, 33, 34]
[33, 34, 35, 36, 37, 38, 39, 40, 41, 42]
[41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


## write a code to convert to onhotEncoding or to onhotEncoding to scaler

In [12]:
import random
y = [random.randint(1,5) for i in range(10)]

In [13]:
print(y)
def onhoteencoding(data):
    length   = len(data)
    meximaum = max(data)
    mask = [[0 for i in range(meximaum)] for k in range(length)]
    for i in range(length):
        mask[i][y[i]-1]=1
    return mask
onhoteencoding(y)

[3, 4, 1, 3, 5, 1, 3, 2, 4, 3]


[[0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0]]

## Write a code to generate a sample dataset with numpy and print all with ramdom index batch size 
* with no repetation on index
* use choice 


In [10]:
import numpy as np
from numpy import random
data = random.random((50,1))*100


## Write a code to generate a sample dataset with numpy and print all with batch size 
* with repetation 


>>>>>>>>>>>>>>>>>>>>>>>>>>>>> for batch 1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.
[14 36  5  4 28 33 38  1  1  8]
[[76.75863604]
 [85.62097583]
 [62.20548277]
 [55.3646004 ]
 [35.62892949]
 [54.81625646]
 [30.46685078]
 [23.98808746]
 [23.98808746]
 [55.70024703]]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> for batch 2>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.
[37 48 32  9 11 31 42 17  8 34]
[[36.33394002]
 [ 9.95362592]
 [79.36766338]
 [25.91231713]
 [63.29109547]
 [40.13713404]
 [95.54638789]
 [21.19032398]
 [55.70024703]
 [68.97304437]]


## Thread two task and finish according to thir time delay

In [42]:
## write your code hear
import threading,time
def Task(name:int,n:int):
    print(f"Job-{name} is started")
    time.sleep(n)
    print(f"This job-{name} takes {n}s to complete! ")
j1 = threading.Thread(target=Task,args=(1,8,))
j2 = threading.Thread(target=Task,args=(2,2,))
j3 = threading.Thread(target=Task,args=(3,5,))
j1.start()
j2.start()
j3.start()


Job-1 is started
Job-2 is started
Job-3 is started


This job-2 takes 2s to complete! 
This job-3 takes 5s to complete! 
This job-1 takes 8s to complete! 


## Reach out nearest gas station 
* refule list have Gas station marked from your stating point 
* distance list current moved distance  
* dselect is a copy of list to decide the sortest gas station mark with index number 


In [47]:
refule     = [10,20,30,40,50]
distance   = [8,15,18,25,50]
dselect     = distance.copy()

In [48]:
for i in range(len(distance)):
  mindist = max(refule)
  for j in range(len(refule)):
    if abs(distance[i]-refule[j]) <= mindist:
      mindist = abs(distance[i]-refule[j])
      dselect[i] = j+1
print(dselect)



[1, 2, 2, 3, 5]


## N place rotation of list elements

In [71]:
rotate = [i for i in range(1,8)]