***
# Basic Assisments
***

##  Write a Python function to check if a number is even

False

##  Write a Python function to find the factorial of a number.

11  is a prime number 


##  Write a Python function to check if a string is a palindrome.

'it is palindrom'

## Write a Python function to return the Fibonacci series up to n terms.

##  Write a Python function to find the HCF
***

###
✅ **Yes, that is an excellent and accurate analogy** for understanding how **HCF works!**
Let me rephrase and expand it slightly to reinforce the concept:

---

### 🎯 Real-World Analogy Using HCF:

**You have:**

* 8 red balls
* 12 green balls

You want to:

* **Pack them into identical boxes** such that:

  * Each box has **the same number of red and green balls**
  * No balls are left over

---

### 🔍 Step-by-Step Thinking:

1. **Find the HCF of 8 and 12**

   * HCF(8, 12) = **4**

2. **What does that mean?**
   You can make **4 identical boxes**.

3. **Distribute balls equally:**

   * Red balls per box = 8 ÷ 4 = **2**
   * Green balls per box = 12 ÷ 4 = **3**

---

### ✅ Final Conclusion:

You can pack **2 red balls and 3 green balls per box**, and:

* You’ll have **4 such boxes**
* **No balls are left over**

---

### 📦 Why this analogy is useful:

* It shows **grouping or distributing** things evenly.
* Helps in understanding how HCF finds the **largest group size** that divides quantities **exactly and equally**.

---

Let me know if you'd like more such analogies (e.g., ropes, chocolates, scheduling events, etc.)!


1

20.0

***
# Intermediate Assisments
***

## Last Nth highest Number

Real   >> [12, 3, 22, 3, 5, 3, 6, 12, 8]
sorted >> [22, 12, 12, 8, 6, 5, 3, 3, 3]
       >> 5th


6

## Check palindrom for string and numbers

## find N perfect square list of numbers

list of perfect Square form 1 to 100


[1, 4, 9, 16, 25, 36, 49, 64, 81]

## Now create a palindrom string or number

## Reverse the numbers

## print N sliding window on given M range also print the reminder if any
- formula (start * size to start * size + size)

To 0 from 10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
To 10 from 20
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
To 20 from 30
[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
To 30 from 40
[31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
To 40 from 50
[41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
reminder 2
[1, 2, 3, 4, 5, 6, 7, 8]


## print N sliding window with overlap of M size
- Take care of even and odd 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
[31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]
[41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


## write a code to convert to onhotEncoding or to onhotEncoding to scaler

In [1]:
import random
y = [random.randint(1,5) for i in range(10)]

[3, 2, 3, 5, 2, 2, 1, 2, 4, 5]


[[0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

## Write a code to generate a sample dataset with numpy and print all with ramdom index batch size 
* with no repetation on index
* use choice 


In [10]:
import numpy as np
from numpy import random
data = random.random((50,1))*100


## Write a code to generate a sample dataset with numpy and print all with batch size 
* with repetation 


>>>>>>>>>>>>>>>>>>>>>>>>>>>>> for batch 1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.
[14 36  5  4 28 33 38  1  1  8]
[[76.75863604]
 [85.62097583]
 [62.20548277]
 [55.3646004 ]
 [35.62892949]
 [54.81625646]
 [30.46685078]
 [23.98808746]
 [23.98808746]
 [55.70024703]]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>> for batch 2>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.
[37 48 32  9 11 31 42 17  8 34]
[[36.33394002]
 [ 9.95362592]
 [79.36766338]
 [25.91231713]
 [63.29109547]
 [40.13713404]
 [95.54638789]
 [21.19032398]
 [55.70024703]
 [68.97304437]]


## Thread two task and finish according to thir time delay

In [ ]:
## write your code hear


This is Task 5 Started now
This is Task 2 Started now
Task: 2 timeup
Task: 5 timeup


## reach out nearest gas station 
* refule list have Gas station marked from your stating point 
* distance list current moved distance  
* dselect is a copy of list to decide the sortest gas station mark with index number 


In [35]:
refule     = [10,20,30,40,50]
distance   = [8,15,29,40,50]
dselect     = distance.copy()

In [36]:
for i in range(len(distance)):
  mindist = max(refule)
  for j in range(len(refule)):
    if abs(distance[i]-refule[j]) < mindist:
      mindist = abs(distance[i]-refule[j])
      dselect[i] = j+1
print(dselect)



[1, 1, 3, 4, 5]
